import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Piton App Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-blue-400'>
        <div className="flex flex-col items-center justify-start w-screen h-screen ">
          <nav className="flex space-x-4 w-300 mb-12 mt-6">
            <Link className="text-2xl " href={'/login'}>Login</Link>
            <Link className="text-2xl " href={'/register'}>Register</Link>
          </nav>
          <h1 className=" text-5xl cl-blue">
            PITON
          </h1>
        </div>
      </main>
    </>
  )
}
